substitutions:
  node_name: devkit-esp32-s3
  node_friendly_name: "DevKit ESP32-S3"
  variant: esp32s3
  gpio_led: GPIO48
  gpio_usrbtn: GPIO0

packages:
  - !include ../base.yaml

light:
  - id: output_led_builtin
    platform: esp32_rmt_led_strip
    num_leds: 1
    chipset: ws2812
    rgb_order: GRB
