substitutions:
  node_name: devkit-esp32-s3
  node_friendly_name: "DevKit ESP32-S3"
  variant: esp32s3
  gpio_led: GPIO48
  gpio_usrbtn: GPIO0

packages:
  - !include ../base.yaml

dashboard_import:
  package_import_url: github://dionisis2014/esphome-templates/blob/master/src/boards/devkit-esp32-s3.yaml
  import_full_config: false

output:
  - id: !remove output_led_builtin

light:
  - platform: esp32_rmt_led_strip
    id: light_led_builtin
    pin: ${gpio_led}
    chipset: ws2812
    rgb_order: GRB
    num_leds: 1
