packages:
  - !include
    file: ../base.yaml
    vars:
      node_name: devkit-esp32
      node_friendly_name: "DevKit ESP32"
      variant: esp32
      gpio_led: GPIO2
      gpio_usrbtn: GPIO0

esphome:
  name_add_mac_suffix: true
