substitutions:
  node_name: supermini-esp32-c3
  node_friendly_name: "SuperMini ESP32-C3"
  variant: esp32c3
  gpio_led: GPIO8
  gpio_usrbtn: GPIO9

packages:
  - !include ../base.yaml

dashboard_import:
  package_import_url: github://dionisis2014/esphome-templates/blob/master/src/boards/supermini-esp32-c3.yaml
  import_full_config: false

output:
  - id: !extend output_led_builtin
    inverted: true
