packages:
  - !include
    file: ../base.yaml
    vars:
      node_name: xiao-esp32-c6
      node_friendly_name: "Xiao ESP32-C6"
      variant: esp32c6
      gpio_led: GPIO15
      gpio_usrbtn: GPIO9

esphome:
  name_add_mac_suffix: true
  on_boot:
    - priority: 800
      then:
        - output.turn_off: output_rf_power

output:
  - id: !extend output_led_builtin
    inverted: true
  - platform: gpio
    id: output_rf_power
    pin: GPIO3

switch:
  - platform: gpio
    id: switch_rf_switch
    name: "Ext Ant"
    pin: GPIO14
    restore_mode: RESTORE_DEFAULT_OFF
    icon: mdi:antenna
    entity_category: config
